
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: https://eurekaservice.apps.de1.bosch-iot-cloud.com/eureka/
#  instance:
#    hostname: eurekaservice.apps.de1.bosch-iot-cloud.com
#    nonSecurePort: 80

# Increase the Hystrix timeout to 60s (for all)
  hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000